name = "IDE and Editor files"
description = "IDE projects, editor configs, plugins"
enabled = true

[sections.jetbrains]
enabled = true
files = [".idea/"]

[sections.vscode]
enabled = true
files = [".vscode/"]
